### ISSUE TITLE
configuration update error

### ISSUE THREAD

**Issue by ToeiRei** [MycroftAI/mycroft-skills#180]
I was trying to sync the configuration, which failed.

debug log says:

```
19:06:11.697 - mycroft.skills.core:wrapper:371 - ERROR - An error occurred while processing a request in ConfigurationSkill
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/mycroft_core-0.9.1-py2.7.egg/mycroft/skills/core.py", line 358, in wrapper
handler(message)
File "/opt/mycroft/skills/skill-configuration/__init__.py", line 46, in handle_update_intent
if self.update():
File "/opt/mycroft/skills/skill-configuration/__init__.py", line 66, in update
config["location"] = location
TypeError: 'NoneType' object does not support item assignment
```

**Comment by btotharye** [comment]
you might want to file this under core and not the skills repo @ToeiRei

**Comment by ToeiRei** [comment]
moved
